### ISSUE TITLE
Units?

### ISSUE THREAD

**Issue by lilleswing** [isayev/ANI1_dataset#1]
What are the units of the energies for this dataset?

**Comment by lilleswing** [comment]
Why does your pre-trained model predict in eV if your dataset is in hartree?

**Comment by Jussmith01** [comment]
Units of the data set are in Ha. The model predicts in Ha. Conversions are to eV through the ASE interface because ASE works in eV. In summary: the pyNeuroChem interface outputs in Ha, the ASE_ANI interface outputs in eV.
