### ISSUE TITLE
How are the "self interaction energies" computed?

### ISSUE THREAD

**Issue by leifjacobson** [isayev/ANI1_dataset#2]
These energies appear in the README file:

Self-interaction atomic energies

H = -0.500607632585 C = -37.8302333826 N = -54.5680045287 O = -75.0362229210

Are these DFT energies at wB97x/6-31g*?  I am unable to reproduce them.   Can you give details about how these numbers were produced?

Thank you.

**Comment by Jussmith01** [comment]
Sorry for the late response. Indeed the ones provided are for the wb97xd functional not wb97x. This was a oversight. However, after pretty extensive testing with wb97x energies it does not seem to hurt or help the results. In the end it seems the network compensates for any differences. If you need them these are the energies I computed and have started using:

H=-0.499321232710
C=-37.8338334397
N=-54.5732824628
O=-75.0424519384
