### ISSUE TITLE
GDB 10 dataset

### ISSUE THREAD

**Issue by proteneer** [isayev/ANI1_dataset#3]
Is it possible for you guys to provide the gdb-10 dataset for our validation work?

**Comment by proteneer** [comment]
Namely, the gdb10 dataset used for the following plot:

Figure 3: Log-log plots of the training, validation, testing, and a random GDB-10 (molecules with 10 heavy
atoms from the GDB-11 database) extensibility testing set total energy errors vs. increasing number of data
points in the training set. The sets of points converge to the final ANI-1 potential presented in this paper,
trained on the full ANI-1 data set.

**Comment by Jussmith01** [comment]
I added it to the repo. Look in the benchmark directory.
